### ISSUE TITLE
Master slide indices

### ISSUE THREAD

**Issue by mjvanderveen** [brucemcpherson/SlidesMerge#2]
This setting seems to be ignored for every slide except the first.

When I enter 1,2,4,5 (only slide 3 should be repeated), it will repeat slides 2,3,4,5 instead.

**Comment by brucemcpherson** [comment]
fixed version 1.0.4

**Comment by mjvanderveen** [comment]
It works now, but currently what happens is:
Slide 1,2,3A,4,5, 3B in that order appear.

So Slide 3 which is the template slide, for which there are 2 rows in the spreadsheet, is repeated 2 times, but they are not together between slides 2 and 4. The second slide 3 (3B) is at the end of the deck

**Comment by brucemcpherson** [comment]
What are you entering specificially in the masters text box? it should be
numeric positional slide numbers starting at 1. What's the significance of
3A and 3B?
