### ISSUE TITLE
Display Slide Only If Data Is Available

### ISSUE THREAD

**Issue by ghost** [brucemcpherson/SlidesMerge#8]
Let's say I have two template slides: A & B. A represents objective information, and B represents debate. 

Example (A): World War Two was from 1939-45

Example (B): Should the U.S. have intervened in World War 1? 

For simplicity's sake, let's say that for every 25 "A" Slides there is 1 "B" slide. However, I don't want 24 empty "B" slides showing up in between. Is there a way to only show "B" slides when there is data in the corresponding cell?

**Comment by brucemcpherson** [comment]
This will be implemented in 1.0.5, along with a checkbox setting on whether to suppress copies of slides with placeholders for which there is no data - default will be not to suppress (current behavior). The data for all placeholders on a particular slide must be missing before it will be suppressed.

**Comment by ghost** [comment]
Outstanding. Thanks!

**Comment by brucemcpherson** [comment]
Implemented. v1.05 will be pushed to the store today

**Comment by ghost** [comment]
Thanks, Bruce! I really appreciate it!

On Tue, Jul 11, 2017 at 2:38 PM Kevin Goldsmith <kevingoldsmith14@gmail.com>
wrote:

> --
Kevin Goldsmith
(432) 638-8962
LinkedIn Profile <https://www.linkedin.com/in/kevingoldsmith91>
